"""
The following sccript is written with the help of Github Copilot (GPT-4.1 mini)
The printing and plotting is generated by Claude Opus-4.5, with the context being the implementation and our intent (plot / print). 
The code is debugged with the help of Claude Opus-4.5, with the context being error logs, intermediate plots and code snippets.
"""
import os
import json
import matplotlib.pyplot as plt

def load_all_curves(curves_dir='./curves'):
    """Load all curve JSON files from the curves directory."""
    all_curves = {}
    
    if not os.path.exists(curves_dir):
        print(f"Curves directory not found: {curves_dir}")
        return all_curves
    
    for filename in os.listdir(curves_dir):
        if filename.endswith('_curves.json') and filename != 'all_curves.json':
            model_name = filename.replace('_curves.json', '')
            filepath = os.path.join(curves_dir, filename)
            try:
                with open(filepath, 'r') as f:
                    all_curves[model_name] = json.load(f)
                print(f"Loaded: {model_name}")
            except Exception as e:
                print(f"Error loading {filepath}: {e}")
    
    return all_curves

def plot_figure6(all_curves, save_path='figure6.png'):
    """Plot training curves in Figure 6 style (3-panel)."""
    colors = {
        'plain-20': 'C0', 'plain-32': 'C1', 'plain-44': 'C2', 'plain-56': 'C3',
        'ResNet-20': 'C0', 'ResNet-32': 'C1', 'ResNet-44': 'C2', 
        'ResNet-56': 'C3', 'ResNet-110': 'C4', 'ResNet-1202': 'C5',
    }
    
    plain_models = [k for k in all_curves.keys() if 'plain' in k]
    resnet_shallow = [k for k in all_curves.keys() if 'ResNet' in k and int(k.split('-')[1]) <= 56]
    resnet_deep = [k for k in all_curves.keys() if 'ResNet' in k and int(k.split('-')[1]) > 56]
    
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    def plot_curves(ax, model_list, title):
        for name in sorted(model_list, key=lambda x: int(x.split('-')[1])):
            if name not in all_curves:
                continue
            curves = all_curves[name]
            color = colors.get(name, 'black')
            depth = name.split('-')[1]
            
            if curves['train']:
                iters, errs = zip(*curves['train'])
                iters = [i / 1e4 for i in iters]
                ax.plot(iters, errs, '--', color=color, linewidth=1, alpha=0.7)
            
            if curves['test']:
                iters, errs = zip(*curves['test'])
                iters = [i / 1e4 for i in iters]
                ax.plot(iters, errs, '-', color=color, linewidth=2, label=f"{depth}-layer")
        
        ax.set_xlabel('iter. (1e4)')
        ax.set_ylabel('error (%)')
        ax.set_title(title)
        ax.legend(fontsize=9, loc='upper right')
        ax.set_ylim(0, 25)
        ax.set_xlim(0, 6.5)
        ax.grid(True, alpha=0.3)
    
    plot_curves(axes[0], plain_models, 'Plain Networks')
    plot_curves(axes[1], resnet_shallow, 'ResNets')
    
    if resnet_deep:
        plot_curves(axes[2], resnet_deep, 'Deep ResNets (110+)')
    else:
        axes[2].text(0.5, 0.5, 'No deep ResNets trained', ha='center', va='center', 
                     transform=axes[2].transAxes, fontsize=12)
        axes[2].set_title('Deep ResNets (110+)')
    
    fig.suptitle('Training on CIFAR-10: Dashed=training error, Solid=test error', fontsize=11)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Figure saved to {save_path}")

def plot_figure6_paper_style(all_curves, save_path='figure6_paper.png'):
    """Plot in exact paper style: 2-panel (plain vs ResNet)."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    
    depth_colors = {20: 'C0', 32: 'C1', 44: 'C2', 56: 'C3', 110: 'C4'}
    
    def plot_panel(ax, prefix, title):
        models = sorted([k for k in all_curves.keys() if k.startswith(prefix)], 
                       key=lambda x: int(x.split('-')[1]))
        
        for name in models:
            curves = all_curves[name]
            depth = int(name.split('-')[1])
            color = depth_colors.get(depth, 'black')
            
            if curves['train']:
                iters, errs = zip(*curves['train'])
                iters = [i / 1e4 for i in iters]
                ax.plot(iters, errs, '--', color=color, linewidth=1, alpha=0.6)
            
            if curves['test']:
                iters, errs = zip(*curves['test'])
                iters = [i / 1e4 for i in iters]
                ax.plot(iters, errs, '-', color=color, linewidth=2.5, label=f"{depth}-layer")
        
        ax.set_xlabel('iter. (1e4)', fontsize=11)
        ax.set_ylabel('error (%)', fontsize=11)
        ax.set_title(title, fontsize=12)
        ax.legend(fontsize=9)
        ax.set_ylim(0, 25)
        ax.set_xlim(0, 6.5)
        ax.grid(True, alpha=0.3)
    
    plot_panel(axes[0], 'plain', 'Plain Networks')
    plot_panel(axes[1], 'ResNet', 'ResNets')
    
    fig.suptitle('Figure 6: Training on CIFAR-10 (Dashed=train, Solid=test)', fontsize=12)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Figure saved to {save_path}")

def main():
    import argparse
    parser = argparse.ArgumentParser(description='Plot Figure 6 from saved curve files')
    parser.add_argument('--curves_dir', type=str, default='./curves',
                        help='Directory containing curve JSON files')
    parser.add_argument('--output', type=str, default='figure6_paper.png',
                        help='Output filename')
    args = parser.parse_args()
    
    print(f"Loading curves from: {args.curves_dir}")
    all_curves = load_all_curves(args.curves_dir)
    
    if not all_curves:
        print("No curves found!")
        return
    
    print(f"\nFound {len(all_curves)} models: {list(all_curves.keys())}")
    
    plot_figure6(all_curves, save_path='figure6.png')
    plot_figure6_paper_style(all_curves, save_path=args.output)

if __name__ == "__main__":
    main()